# see: https://www.appveyor.com/docs/appveyor-yml/
version: AppVeyor-{build}
skip_tags: true
skip_branch_with_pr: true

build_script:
  - build.bat

deploy:
  release: builder-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release of pentest tools tag created by AppVeyor build $(appveyor_build_version). Pass: $(_7Z_PASSWORD_)'
  provider: GitHub
  auth_token:
    secure: Ud4Jsv5IpT4+8zy5SPHn/HUphV6414u713Q7tZL1J2TTWE9yDdnKCUUeBVcYY3dP # your encrypted token from GitHub
  # see https://www.appveyor.com/docs/packaging-artifacts/#packaging-multiple-files-in-different-locations-into-a-single-archive
  #artifact: '*.7z'
  draft: false
  prerelease: false
  force_update: true